image: Visual Studio 2022
version: '{build}'

init:
  - git config --global core.autocrlf true

branches:
  only:
    - master

environment:
  global:
    # https://stackoverflow.com/questions/42024619/maven-build-gets-connection-reset-when-downloading-artifacts
    MAVEN_OPTS: "-Dhttp.keepAlive=false -Dmaven.wagon.http.retryHandler.count=3"
  matrix:
    - JAVA_HOME: C:\Program Files\Java\JDK21

build_script:
  - mvn --batch-mode clean package -DskipTest
test_script:
  - mvn --batch-mode clean verify
